apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "techself.fullname" . }}
  labels:
    {{- include "techself.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "techself.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "techself.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "techself.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: 80
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
